// React_sec/src/page/employee.js
import React,{ useState } from 'react';
// import { Table } from "semantic-ui-react";
// import contacts from '../page/data.json';
import { MDBBtn,
    MDBModal,
    MDBModalDialog,
    MDBModalContent,
    MDBModalHeader,
    MDBModalTitle,
    MDBModalBody,
    MDBModalFooter,
  } from 'mdb-react-ui-kit';
import { Action } from 'history';
import { MDBInput } from 'mdb-react-ui-kit';






class employee extends React.Component {


  constructor(props) {
    super(props);

    this.state = {
      form: {
        firstName: props.firstName,
        lastName: props.lastName,
        email: props.mail,
        mobile: props.phone,
        dob:props.dob
      }
    }


    this.state2 = {
      people: [
        { "id" :1 ,"firstName": "John", "lastName": "Doe", "dob": "12/12/2010" ,"email":"john@gmail.com","mobile":"9788331203"},
        { "id" :2 ,"firstName": "Michael", "lastName": "Smith", "dob": "12/12/2010","email":"michael@gmail.com" ,"mobile":"9788331203"},
        { "id" :3 ,"firstName": "Carol", "lastName": "Jordan", "dob": "12/12/2010","email":"michael@gmail.com","mobile":"9788331203" },
        { "id" :4 , "firstName": "Tanya", "lastName": "Blake", "dob": "12/12/2010","email": "tanya@gmail.com","mobile":"9788331203"}
    ]
    };
    
  }
  

  contacts=[
    { "id" :1 ,"firstName": "John", "lastName": "Doe", "dob": "12/12/2010" ,"email":"john@gmail.com","mobile":"9788331203"},
    { "id" :2 ,"firstName": "Michael", "lastName": "Smith", "dob": "12/12/2010","email":"michael@gmail.com" ,"mobile":"9788331203"},
    { "id" :3 ,"firstName": "Carol", "lastName": "Jordan", "dob": "12/12/2010","email":"michael@gmail.com","mobile":"9788331203" },
    { "id" :4 , "firstName": "Tanya", "lastName": "Blake", "dob": "12/12/2010","email": "tanya@gmail.com","mobile":"9788331203"}

]




    


n=4;

  changeFirstName(event) {
    var form        = this.state.form;
    
    form.firstName  = event.target.value;
   
    this.setState({ form: form });
    // console.log(form.firstName);
  }
  changeLastName(event) {
    var form        = this.state.form;
    form.lastName  = event.target.value;

    this.setState({ form: form });
  }
  changeMail(event) {
    var form        = this.state.form;
    form.email  = event.target.value;

    this.setState({ form: form });
    
  }
  changephone(event) {
    var form        = this.state.form;
    form.mobile  = event.target.value;

    this.setState({ form: form });
  }
  changeDob(event) {
    var form        = this.state.form;
    form.dob  = event.target.value;

    this.setState({ form: form });
  }
  formSubmitted() {

    // alert("good : "+this.state.form.firstName+" "+this.state.form.lastName+" "+this.state.form.mail+" "+this.state.form.phone+" "+this.state.form.dob);
      console.log(this.state.form);
      console.log(this.state.form.firstName);
      console.log(this.state.form.lastName);
      console.log(this.state.form.email);
      console.log(this.state.form.mobile);
      console.log(this.state.form.dob);
     

    this.contacts.push(this.state.form);
    console.log(this.contacts[this.n]);
    this.state2.people.push(this.state.form);
    console.log("----");
    console.log(this.state2.people);
    this.contacts = this.contacts;
    this.n++;
    for (let i = 0; i < this.contacts.length; i++) {
      console.log(this.contacts[i]);
    }  
    
  }

  getPeople() {
    // fetch("https://jsonplaceholder.typicode.com/users")
    //   .then(response => response.json())
    //   .then(response => this.setState({ people: response }))
    //   .catch(error => console.log(error));

      this.setState({ people: this.state2.people })
  }
  

  reset(){
      console.log("Reset");
      
      // this.state.form.firstName="";
      // this.state.form.lastName="";
      // this.state.form.dob="";
      // this.state.form.email="";
      // this.state.form.mobile="";
      // document.getElementById("firstname").val="";
      // console.log("firstname : "+document.getElementById("firstname").val );
  }





    demo(){
        console.log("good");
    
        for (let i = 0; i < this.contacts.length; i++) {
            console.log(this.contacts[i]);
            console.log(this.contacts[i].firstName);
          }
          // contacts.push(this.state);
          var form        = this.state.form;
          console.log(form.firstName);
    }

    tableOnLoad(){
      console.log("OnLoad");
    }

    

        
    render(){

      return (<>
      <br></br>
     
      <h1 class="border border-primary blue rounded-5 text-center">Employee Details Form</h1><br></br>
      {/* Model called from model.js */}
       
               {/* Model */}
          {/* Button trigger modal  */}
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          ADD
        </button>
        <button onClick={this.demo}>Demo</button>
            <div class="container alert border-primary rounded-5">
                <table mdbTable datatable class="row-border hover w-100" onLoad={this.tableOnLoad}>
                    <thead >
                        <tr class="blue border-primary rounded-5">
                        <th>ID</th>   
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Date Of Birth</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th>Action</th>
                        </tr>
                    </thead>
                <tbody>
         
            {this.contacts.map(el => {
            return (
              <tr>
               <td>{el.id+1}</td>
               <td>{el.firstName} </td>
               <td>{el.lastName}</td>
               <td>{el.dob}</td>
               <td>{el.email}</td>
               <td>{el.mobile}</td>
               <td>
                   <button class= "btn btn-danger ml-2"> Delete</button>
                    <button type="button" class="btn btn-primary px-2 ml-2">Update</button>
               </td>
              </tr>
             
            );
          })}
          </tbody>
          </table>
        </div>

        {/* Trial */}

        <table>
          <thead>
            <tr>
              <th>LP</th>
              <th>USER</th>
              <th>EMAIL</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {this.state2.people.map((person, index) => {
              return (
                <tr key={person.email}>
                  <th>{index + 1}</th>
                  <td>{person.firstName}</td>
                  <td>{person.lastName}</td>
                  <td>{person.email}</td>
                  <td>{person.mobile}</td>
                  <td>{person.dob}</td>

                  {/* <td>
                    <button onClick={this.deletePerson(this.state2.people.email)}>
                      Delete
                    </button>
                  </td> */}
                </tr>
              );
            })}
          </tbody>
        </table>

        {/* --------------------Model------------------------ */}
       

        {/* <!-- Modal --> */}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
              {/* <form>
                <div class="container border border-primary px-2 py-2 rounded-5 w-100">
                    <div class="col-sm-12 px-2 py-2 alert alert-success">
                            <p class="text-center">
                            Enter Employee Details
                            </p>
                    </div>
                
                    
                    <div class="row px-2">
                        <div class="md-form mt-0 form-outline" >
                        
                        <MDBInput label='First Name' id='form1' type='text'pattern="[a-zA-Z ]{2,}$" 
                        value={this.state.form.firstName} onChange={this.changeFirstName.bind(this)}/> 
                    </div>
                    </div>
                
                    <div class="row px-2">
                        <div class="md-form mt-0 form-outline" >
                    
                        <MDBInput label='Last Name' id='form1' type='text'pattern="[a-zA-Z ]{2,}$" 
                        value={this.state.form.lastName} onChange={this.changeLastName.bind(this)}/> 
                    </div>
                    </div>
                
                    <div class="row px-2">
                        <div class="md-form mt-0 form-outline" >
                        <MDBInput label='Email Id' id='form1' type='text' pattern="[a-z0-9._%+-]+@[a-z0-9.-]{2,}$" 
                        value={this.state.form.email} onChange={this.changeMail.bind(this)}/> 
                    </div>
                    </div>
                
                        <div class="row px-2">
                            <div class="md-form mt-0 form-outline" >
                            <MDBInput label='Mobile Number' id='form1' type='number' 
                            value={this.state.form.mobile} onChange={this.changephone.bind(this)} /> 
                        </div>
                    </div>
                    
                        <div class="row px-2">
                        <div class="md-form mt-0 form-outline" >
                        <MDBInput label='DOB' id='form1' type='date' value="01/01/2001" 
                        value={this.state.form.dob} onChange={this.changeDob.bind(this)}/> 
                        </div>
                    </div>

                    <div class="row">
                            <div class="col-6">
                                <button type="button" class="btn btn-primary w-100" onClick={this.formSubmitted.bind(this)}
                                
                                >Submit</button>
                            </div>
                            <div class="col-6">
                                <button type="reset" class="btn btn-warning w-100">Reset</button>
                            </div>
                        </div>
                    </div>

                 </form>    */}

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>
       

       {/* Form data */}
       <form ref="form2">
                <div class="container border border-primary px-2 py-2 rounded-5 w-100">
                    <div class="col-sm-12 px-2 py-2 alert alert-success">
                            <p class="text-center">
                            Enter Employee Details
                            </p>
                    </div>
                
                    
                    <div class="row px-2">
                        <div class="md-form mt-0 form-outline" >
                        
                        <MDBInput label='First Name' id="firstname" type='text'pattern="[a-zA-Z ]{2,}$" 
                        value={this.state.form.firstName} onChange={this.changeFirstName.bind(this)}/> 
                    </div>
                    </div>
                
                    <div class="row px-2">
                        <div class="md-form mt-0 form-outline" >
                    
                        <MDBInput label='Last Name' id='lastname' type='text'pattern="[a-zA-Z ]{2,}$" 
                        value={this.state.form.lastName} onChange={this.changeLastName.bind(this)}/> 
                    </div>
                    </div>
                
                    <div class="row px-2">
                        <div class="md-form mt-0 form-outline" >
                        <MDBInput label='Email Id' id='email' type='text' pattern="[a-z0-9._%+-]+@[a-z0-9.-]{2,}$" 
                        value={this.state.form.email} onChange={this.changeMail.bind(this)}/> 
                    </div>
                    </div>
                
                        <div class="row px-2">
                            <div class="md-form mt-0 form-outline" >
                            <MDBInput label='Mobile Number' id='mobile' type='number' 
                            value={this.state.form.mobile} onChange={this.changephone.bind(this)} /> 
                        </div>
                    </div>
                    
                        <div class="row px-2">
                          <div class="md-form mt-0 form-outline" >
                          <MDBInput label='DOB' id='dob' type='date' value="01/01/2001" 
                          value={this.state.form.dob} onChange={this.changeDob.bind(this)}/> 
                          </div>
                    </div>

                    <div class="row">
                            <div class="col-6">
                                <button type="button" class="btn btn-primary w-100" 
                                 onClick={this.formSubmitted.bind(this)}
                                >Submit</button>
                            </div>
                            <div class="col-6">
                                <button type="reset" class="btn btn-warning w-100" onClick={this.reset.bind(this)}>Reset</button>
                            </div>
                        </div>
                    </div>

                 </form>   
           

           
       </> );

    }

}


export default employee;

// First-Sample-project/src/app/employee/employee.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-employee',
  templateUrl: './employee.component.html',
  styleUrls: ['./employee.component.scss']
})
export class EmployeeComponent implements OnInit {

  imageSrc = 'assets/images/img1.jpg';
  pic_csk = "assets/images/csk3.jpg";

  dtOptions: DataTables.Settings = {};
  posts:any;

  data: Array<any>;

  firstname="peter";
  lastname="son";
  dob="12/12/2021";
  email="peter@gmail.com";
  mobile="9788331203";

  constructor(private http: HttpClient) { 
    this.data = [
      { firstName: 'John', lastName: 'Doe', dob: '12/12/2010' ,email:'john@gmail.com',mobile:'9788331203'},
      { firstName: 'Michael', lastName: 'Smith', dob: '12/12/2010',email:'michael@gmail.com' ,mobile:'9788331203'},
      { firstName: 'Michael', lastName: 'Jordan', dob: '12/12/2010',email:'michael@gmail.com',mobile:'9788331203' },
      { firstName: 'Tanya', lastName: 'Blake', dob: '12/12/2010',email: 'tanya@gmail.com',mobile:'9788331203'}
  ];
  }
  
  ngOnInit(): void {
    this.dtOptions = {
      pagingType: 'full_numbers',
      pageLength: 5,
      processing: true
    };
  
    // this.http.get('http://jsonplaceholder.typicode.com/posts')
    //   .subscribe(posts => {
    //     this.posts = posts;
    // });
  }

  getData(form:NgForm){
    console.log(form);
    this.data.push(form);
  }
  
 
 

}

<app-header></app-header>


<h1 class="border border-primary blue rounded-5 text-center">Employee Details Form</h1><br>

  <!-- Button trigger modal -->
  <div class="container">
  <button type="button" class="btn btn-primary px-20" data-toggle="modal" data-target="#exampleModal">
    Add
  </button>
  </div>


<!-- Table part Normal  -->
<!-- <div class="container alert border-primary rounded-5">
    <table datatable mdbTable id="myTable" class="border-primary mt-2 hover" [dtOptions]="dtOptions">
      <thead class="blue">
       
        <td class="col-3"> First Name</td>
        <td  class="col-3"> Last Name </td>
        <td  class="col-3"> Date of Birth</td>
        <td  class="col-3"> Email</td>
        <td  class="col-3"> MObile </td>
      
      </thead>
      <tbody id="tbody">
        
        <tr mdbTableCol *ngFor="let emp of data">
            <td >{{emp.firstName}}</td>
            <td> {{emp.lastName}}</td>
            <td> {{emp.dob}}</td>
            <td> {{emp.email}}</td>
            <td> {{emp.mobile}}</td>
        </tr> 
        
      </tbody>
    </table>
  </div> -->

<!-- table part end -->

<!-- employeee details added part -->


  <!-- ----------------------Models------------------------- -->


<!-- Modal  Add Employeee-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="reset" class="close" aria-label="Close" (click)="getData(empModel.value)" 
            data-dismiss="modal" [disabled]="empModel.form.invalid">
          <span aria-hidden="false">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
       
        <!-- -----Form start ----- -->
<!-- [formGroup]="addForm" -->
        <form  #empModel="ngForm" (submit)="getData(empModel.value)" onload="reset">
          <div class="container border border-primary px-2 py-2 rounded-5 w-100">
              <div class="col-sm-12 px-2 py-2 alert alert-success">
                <p class="text-center">
                  Enter Employee Details
                </p>
                </div>
          
              <!--formControlName='firstName'  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input mdbInput type="text" name="firstName"  class="form-control" id="firstname" [(ngModel)] = "employee.firstName"
                  #firstName="ngModel"  pattern="[a-zA-Z ]{1,}$" [class.is-invalid]="firstName.invalid && firstName.touched"
                   required ngModel >
                  <label for="firstname" >First Name</label>
                  <div class="invalid-feedback" id="div_firstname">
                      Enter Your First Name !!
                  </div> 
               </div>
              </div>
          <!--  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input  type="text" name="lastName" class="form-control" id="lastname" [(ngModel)] = "employee.lastName"
                    #lastname="ngModel" pattern="[a-zA-Z ]{1,}$" [class.is-invalid]="lastname.invalid && lastname.touched"
                    required ngModel mdbInput>
                  <label for="lastname" class="">Last Name</label>
                  <div class="invalid-feedback" id="div_lastname">
                      Enter Your Last Name !!
                  </div> 
               </div>
              </div>
            <!--  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input type="email" id="email" class="form-control" name="email" [(ngModel)] = "employee.email"
                    pattern="[a-z0-9._%+-]+@[a-z0-9.-]{2,}$" #email="ngModel" 
                    [class.is-invalid]="email.invalid && email.touched" mdbInput ngModel required>
                <label for="email">Your Mail Id</label>
                <div class="invalid-feedback">
                  Enter Your Proper Mail Id (like: "john@mail")
              </div> 
               </div>
              </div>
            <!-- pattern="[0-9]{10,10}$" --> 
            <!--  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input type="number" id="mobile" class="form-control" name="mobile" [(ngModel)]= "employee.mobile"
                  #mobile="ngModel"   [class.is-invalid]="mobile.invalid && mobile.touched" 
                  mdbInput ngModel required>
                  <label for="mobile">Your Mobile Number</label>
                  <div class="invalid-feedback">
                    Enter Your Mobile (10 Digit only) !! 
                </div> 
               </div>
              </div>
               <!--  -->
                <div class="row px-2">
                  <div class="md-form mt-0 form-outline" >
                    <input  type="date" name="dob" class="form-control" id="dob" [(ngModel)] = "employee.dob"
                    #dob="ngModel" pattern="[0-9+-+0-9+-0-9]{10,10}$"  [class.is-invalid]="dob.invalid && dob.touched" 
                     required ngModel mdbInput>
                    <label for="dob">Date of Birth</label>
                    <div class="invalid-feedback" id="div_dob">
                        Enter Your Date of Birth !!
                    </div> 
                 </div>
               </div>
               
               <div class="row px-2">
                  <div class="col-12">
                    <button type="reset" class="btn btn-warning w-100">Reset </button>
                  </div>
                </div> 

          </div> 

          </form>

        <!-- Form Ends -->
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary" (click)="getData(empModel.value)" 
          data-dismiss="modal" [disabled]="empModel.form.invalid">Save </button>
        </div>
    </div>
    
  </div>
</div>


<br>
<div class="container alert border-primary rounded-5">
<table mdbTable datatable [dtOptions]="dtOptions" class="row-border hover ">
  <thead class="blue">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Date Of Birth</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let post of data" (click)="onSelect(post)">
      <td>{{ post.firstName }}</td>
      <td>{{ post.lastName }}</td>
      <td>{{ post.dob }}</td>
      <td>{{ post.email }}</td>
      <td>{{ post.mobile }}</td>
      <td>
        <button (click)="deleteEmployee(post.id)" 
          class = "btn btn-danger ml-2" style="margin-left: 5px"> Delete</button>
          <button type="button" class="btn btn-primary px-2 ml-2" data-toggle="modal" (click)="getID(post.id)"
            data-target="#exampleModal_2">
            Update
          </button>
      </td>
    </tr>
  </tbody>
</table>
</div>
<br>
<!-- showData() -->
<button (click)="demoButton()">Demo</button>
<br><br><br>
<br><br><br>
<!-- ------------------===models end------------------------ -->


<!-- Model for Update the Employeee details   -->

<div class="modal fade" id="exampleModal_2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="reset" class="close" aria-label="Close" (click)="getData(empModel.value)" 
            data-dismiss="modal" [disabled]="empModel.form.invalid">
          <span aria-hidden="false">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      
       
        <!-- -----Form start ----- -->
<!-- [formGroup]="addForm" -->
        <form #empModel="ngForm" (submit)="getData(empModel.value)" onload="reset">
          <div class="container border border-primary px-2 py-2 rounded-5 w-100">
              <div class="col-sm-12 px-2 py-2 alert alert-success">
                <p class="text-center">
                  Update Employee Details
                </p>
                </div>
          
              <!--  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input mdbInput type="text" name="firstName" class="form-control" id="firstname" [(ngModel)] = "employee.firstName"
                  #firstName="ngModel"  pattern="[a-zA-Z ]{1,}$" [class.is-invalid]="firstName.invalid && firstName.touched"
                   required ngModel >
                  <label for="firstname" >First Name</label>
                  <div class="invalid-feedback" id="div_firstname">
                      Enter Your First Name !!
                  </div> 
               </div>
              </div>
          <!--  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input  type="text" name="lastName" class="form-control" id="lastname" [(ngModel)] = "employee.lastName"
                    #lastname="ngModel" pattern="[a-zA-Z ]{1,}$" [class.is-invalid]="lastname.invalid && lastname.touched"
                    required ngModel mdbInput>
                  <label for="lastname" class="">Last Name</label>
                  <div class="invalid-feedback" id="div_lastname">
                      Enter Your Last Name !!
                  </div> 
               </div>
              </div>
            <!--  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input type="email" id="email" class="form-control" name="email" [(ngModel)] = "employee.email"
                    pattern="[a-z0-9._%+-]+@[a-z0-9.-]{2,}$" #email="ngModel" 
                    [class.is-invalid]="email.invalid && email.touched" mdbInput ngModel required>
                <label for="email">Your Mail Id</label>
                <div class="invalid-feedback">
                  Enter Your Proper Mail Id (like: "john@mail")
              </div> 
               </div>
              </div>
            <!-- pattern="[0-9]{10,10}$" --> 
            <!--  -->
              <div class="row px-2">
                <div class="md-form mt-0 form-outline" >
                  <input type="number" id="mobile" class="form-control" name="mobile" [(ngModel)]= "employee.mobile"
                  #mobile="ngModel"   [class.is-invalid]="mobile.invalid && mobile.touched" 
                  mdbInput ngModel required>
                  <label for="mobile">Your Mobile Number</label>
                  <div class="invalid-feedback">
                    Enter Your Mobile (10 Digit only) !! 
                </div> 
               </div>
              </div>
               <!--  -->
                <div class="row px-2">
                  <div class="md-form mt-0 form-outline" >
                    <input  type="date" name="dob" class="form-control" id="dob" [(ngModel)] = "employee.dob"
                    #dob="ngModel" pattern="[0-9+-+0-9+-0-9]{10,10}$"  [class.is-invalid]="dob.invalid && dob.touched" 
                     required ngModel mdbInput>
                    <label for="dob">Date of Birth</label>
                    <div class="invalid-feedback" id="div_dob">
                        Enter Your Date of Birth !!
                    </div> 
                 </div>
               </div>
               
               <div class="row px-2">
                  <div class="col-12">
                    <button type="reset" class="btn btn-warning w-100">Reset </button>
                  </div>
                </div> 

          </div> 

          </form>

        <!-- Form Ends -->
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-primary" (click)="updateEmployee()" 
          data-dismiss="modal" [disabled]="empModel.form.invalid">Update </button>
        </div>
    </div>
    
  </div>
</div>



<!-- Model ends for  update details     -->

<footer class="page-footer font-small blue pt-4 fixed-bottom">
  <div class="footer-copyright text-center py-3">© 2022 Copyright:
      <a href="https://mdbootstrap.com/"> Company.com</a>
    </div>
  </footer>
