// First-Sample-project/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import {Router} from '@angular/router';
import { FormGroup, FormControl, Validators } from '@angular/forms';  


@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  data:Array<any>;
  

  constructor(private router:Router) {
    this.data=[{email:"",pass:""}]
   }

  ngOnInit(): void {
  }
  onValidate(form:NgForm){
    console.log(form);
    this.data.push(form);
    console.log(this.data[1]["email"]);
    this.router.navigate(['/employee']);
  }

  onSubmit(form:NgForm){
    alert("working");
  }
  


}


<header class="page-header font-small blue pt-4">
<div class="rounded-5 text-center"><strong style="font-size: 30px;">Login</strong></div>
</header>
<div class="container py-2 p-3 align-items-center rounded-5 float-sm-none w-50" >
    <form mdbForm class="" #getData="ngForm" (ngSubmit)="onValidate(getData.value)" novalidate>
        <div class="row py-5">
            <div class="col-md-8" >
                <div class="md-form mt-0 form-outline" >
                    <mdb-icon fas icon="envelope" class="prefix"></mdb-icon>
                    <input type="email" id="tb_email" class="form-control" pattern="[a-z0-9._%+-]+@[a-z0-9.-]{2,}$" 
                      #email="ngModel" [class.is-invalid]="email.invalid && email.touched" name="email" 
                      ngModel required mdbInput>
                    <label for="tb_email" class="">Email Id</label>
                    <div class="invalid-feedback" id="div_email">
                        Enter Your Proper Mail Id (like: "john@mail")
                    </div> 
                </div>
            </div>
        </div>
        <!-- ^[a-z0-9_-]{8,15}$ -->
        <div class="row py-5">
            <div class="col-md-8" >
                <div class="md-form mt-0 form-outline">
                    <mdb-icon fas icon="key" class="prefix"></mdb-icon>
                    <input type="password" id="tb_pass" class="form-control" pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,15}$" 
                        #pass="ngModel" [class.is-invalid]="pass.invalid && pass.touched" name="pass"
                        autocomplete="on" ngModel required mdbInput>
                    <label for="tb_pass" class="">Password</label>
                <div class="invalid-feedback" id="div_pass">
                   Password must be 8 to 15 length(1 symbol,1 caps, 1 small and 1 number )
                  </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                <button type="submit" class="btn btn-success w-100" id="submit" [disabled]="getData.form.invalid">Login</button>
            </div>
            <div class="col-4">
                <button type="reset" class="btn btn-warning w-100" >Reset</button>
            </div>
        </div>
        

    </form>


</div>

<br><br>
<footer class="page-footer font-small blue pt-4 fixed-bottom">
    <div class="footer-copyright text-center py-3">© 2022 Copyright:
        <a href="https://mdbootstrap.com/"> Company.com</a>
    </div>
</footer>





<router-outlet></router-outlet>

// React_sec/src/page/login.js
import React from 'react';
import {MDBIcon} from "mdbreact";

import { MDBInput } from 'mdb-react-ui-kit';

class login extends React.Component{

    constructor(props) {
        super(props);
        this.state = {
            login: {
              userName: props.userName,
              password: props.password,
              }
          }
      }
    
      handleUserNameChanged(event) {
        var login        = this.state.login;
        login.userName  = event.target.value;
        this.setState({ login: login });
      }

      handlePasswordChanged(event) {
        var login        = this.state.login;
        login.password  = event.target.value;
        this.setState({ login: login });
      }
    
      handleButtonClicked() {
        console.log(this.state.login);
        console.log(this.state.login.userName);
        console.log(this.state.login.password);
        window.location.replace("http://localhost:3000/form");
        
      }
   
    render() {
    return (<><h1 class="border border-primary blue rounded-5 text-center">Login Form</h1><br></br>
   
  
        {/* Login Form Page code */}

<div class="container py-2 p-3 align-items-center rounded-5 float-sm-none w-50" >     
    <form mdbForm class="" novalidate>
        <div class="row py-5">
            <div class="col-md-8" >
                <div class="md-form mt-0 form-outline" >
                    <MDBIcon fas icon="envelope" />
                    <MDBInput label='Email Id' id='form1' type='text'pattern="[a-z0-9._%+-]+@[a-z0-9.-]{2,}$" name="email" value={this.state.login.userName} 
                      onChange={this.handleUserNameChanged.bind(this)} />
                   
                </div>
            </div>
        </div>

        <div class="row py-5">
            <div class="col-md-8" >
                <div class="md-form mt-0 form-outline">
                <MDBIcon fas icon="key" />
                    <MDBInput label='Password' id='form1' type='password' pattern="^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,15}$" name="pass" value={this.state.login.password} 
                        onChange={this.handlePasswordChanged.bind(this)} autocomplete="on"/>
                  </div>
            </div>
        </div>

        <div class="row">
            <div class="col-4">
                <button class="btn btn-primary w-100" >Sign Up</button>
            </div>
            <div class="col-4">
                <button type="submit" class="btn btn-primary w-100" id="submit" 
                onClick={this.handleButtonClicked.bind(this)}>Sign In</button>
            </div>          
        </div>
    </form>
</div>

    </>
        );
    }
  }
  
  export default login;
