// React_sec/src/page/header.js
import React from 'react';
import { MDBBtn } from 'mdb-react-ui-kit';
import { MDBDropdownToggle, MDBDropdown,
  MDBAvatar, MDBDropdownMenu, MDBDropdownItem
} from "mdbreact";




class header extends React.Component {
  render(){
    return (<>
    <br></br>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" onClick="demo()">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">about</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></hr></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>


    
     {/* Anchor tag role button and class related button and href can be accept... */}
      <a class="btn btn-primary mx-2" href="/" role="button">Anchor tag role Button (Header page)</a>

      {/* Anchor tag outside new button inside,  */}
      <a href="/home"><button type="button" class="btn btn-primary px-2 mx-2"style={{width:'80px'}} >Home</button></a>  
      <a href="/about"><button type="button" class="btn btn-primary mx-2" style={{width:'155px'}}>About</button></a>  
      <a href="/login" class="btn btn-primary mx-2" role="button" style={{width:'155px'}}>Login</a>
      <a href="/form" class="btn btn-primary mx-2" role="button" style={{width:'155px'}}>Form</a>
      <a href="/form2" class="btn btn-primary mx-2" role="button" style={{width:'155px'}}>Form 2</a>
      <a href="/feedback" class="btn btn-primary mx-2" role="button" style={{width:'155px'}}>FeedBack</a>
      <a href="/employee" class="btn btn-primary mx-2" role="button" style={{width:'155px'}}>Employee</a>
      <a href="/sports" class="btn btn-primary mx-2" role="button" style={{width:'155px'}}>Sports</a>
      <a href="/form3" class="btn btn-primary mx-2" role="button" style={{width:'155px'}}>Form3</a>
      
      <hr></hr>
    </>
        );
        
       
  };
}
  
  export default header;

// First-Sample-project/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {

  pic_csk = "assets/images/csk3.jpg";

  constructor() { }

  ngOnInit(): void {
  }

}



<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark indigo rounded-5 sticky-top">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="#">
          <img src="{{pic_csk}}" class="rounded-8" style="width:40px;height:40px"/>
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" routerLink="/">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/employee">Employees</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/sport">Sports</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/feedback">Feedback</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/about">About us</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->
  
      <!-- Right elements -->
      <div class="d-flex align-items-center">
        <!-- Icon -->
        <a class="text-reset me-3" href="#">
          <i class="fas fa-shopping-cart"></i>
        </a>
  
        <!-- Notifications -->
        <a
          class="text-reset me-3 dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">1</span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" routerLink="/">Login</a>
          </li>
          <li>
            <a class="dropdown-item" routerLink="/employee">Employees</a>
          </li>
          <li>
            <a class="dropdown-item" routerLink="/sport">Sports</a>
          </li>
          <li>
            <a class="dropdown-item" routerLink="/feedback">Feedback</a>
          </li>
          <li>
            <a class="dropdown-item" routerLink="/about">About us</a>
          </li>
        </ul>
  
        <!-- Avatar -->
        <a
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="https://mdbootstrap.com/img/new/avatars/2.jpg"
            class="rounded-circle"
            height="25"
            alt=""
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
        <li>
          <a class="dropdown-item" routerLink="/">Login</a>
        </li>
        <li>
          <a class="dropdown-item" routerLink="/employee">Employees</a>
        </li>
        <li>
          <a class="dropdown-item" routerLink="/sport">Sports</a>
        </li>
        <li>
          <a class="dropdown-item" routerLink="/feedback">Feedback</a>
        </li>
        <li>
          <a class="dropdown-item" routerLink="/about">About us</a>
        </li>
        </ul>
      </div>
      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->
